### ISSUE TITLE
Mac OS X Build Instructions in Monterry

### ISSUE THREAD

**Issue by scolcoin** [CoinBlack/blackcoin-more#1]
hello
I have not been able to compile in MAC monterry could you help me https://github.com/CoinBlack/blackcoin-more/blob/master/doc/build-osx.md

**Comment by michelvankessel** [comment]
Hi, I have to look into this. Give me a few days

**Comment by michelvankessel** [comment]
I don't know about Brew, but I can compile it with macports. 

first install the dependencies:

sudo port install autoconf boost173 openssl11 automake libtool pkgconfig python39 py39-pip boost-build wget miniupnpc zmq-devel protobuf-cpp gperf libevent db62 qrencode imagemagick qt5

sudo port install autoconf boost171 automake libtool pkgconfig python39 py39-pip boost-build wget miniupnpc zmq-devel protobuf-cpp gperf libevent db62 qrencode qt5 librsvg openssl11

./autogen.sh
./configure --enable-reduce-exports  --with-boost=/opt/local/libexec/boost/1.71/
make -j4 
make deploy

The current Blackcoin version doesn't compile against Boost1.73 and higher.

**Comment by scolcoin** [comment]
Thank you very much, I'll try it

**Comment by scolcoin** [comment]
perfect!
