### ISSUE TITLE
Syncing Blackcoin More 25.1 results in out of memory condition

### ISSUE THREAD

**Issue by CryptoBlackcoin** [CoinBlack/blackcoin-more#11]
I am running Ubuntu 22.04 on a Raspberry Pi 4B with 4GB RAM. I was not able to sync the chain in one go.
I had to restart the application at least 3 times.

**Comment by BlackcoinDev** [comment]
investigating issue!

**Comment by expatjedi** [comment]
> I am running Ubuntu 22.04 on a Raspberry Pi 4B with 4GB RAM. I was not able to sync the chain in one go. I had to restart the application at least 3 times.

Could you run the command below and show us the output please?

`sudo dmesg | grep -i memory`

**Comment by CryptoBlackcoin** [comment]
remember it happens during sync

```sudo dmesg | grep -i memory
[    0.000000] Reserved memory: created CMA memory pool at 0x0000000019800000, size 320 MiB
[    0.000000] Early memory node ranges
[    0.000000] Memory: 3523060K/4050944K available (14336K kernel code, 2668K rwdata, 5208K rodata, 5760K init, 879K bss, 200204K reserved, 327680K cma-reserved)
[    0.696062] Freeing initrd memory: 24492K
[    0.887563] Freeing unused kernel memory: 5760K
[   15.150350] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
```

**Comment by expatjedi** [comment]
I don't think that daemon crash is related with memory. We would have been see the error clearly if its the issue.

**Comment by CryptoBlackcoin** [comment]
> I don't think that daemon crash is related with memory. We would have been see the error clearly if its the issue.

I think it is related to memory. systemd-oom kicks in.

**Comment by CryptoBlackcoin** [comment]
another attempt...crashed at same stage:

```
Synchronizing blockheaders, height: 4676000 (~99.10%)
UpdateTip: new best=00000c0dfe0ea4bdf83516e2170bf950f8184392766ac70a26d4aa4a394c1570 height=1 version=0x00000006 log2_work=21.000001 tx=2 date='2014-02-24T06:00:25Z' progress=0.000000 cache=0.0MiB(1txo)
```

**Comment by BlackcoinDev** [comment]
Hi, please try this

`./blackmore-qt -dbcache=3072`

This will run Blackcoin More with more databse sync cache. Please let us know it this helps.

Also, please try difference values.

**Comment by BlackcoinDev** [comment]
I can confirm this issue doesn´t occur in v26.1.0-beta-1 

Please upgrade https://github.com/CoinBlack/blackcoin-more/releases/tag/v26.0.0-beta-1
