### ISSUE TITLE
[26.2] After Segwit activation, nodes stop sending transactions to other nodes

### ISSUE THREAD

**Issue by lateminer** [CoinBlack/blackcoin-more#23]
After the activation of Segwit, if a node detects another node with the `NODE_SEGWIT` flag, it stops sending transactions to it. As a result, the blocks become empty, with transactions excluded.

JSON example:
```
  {
    "direction": "sent",
    "time": 1726324908306200,
    "size": 169,
    "msgtype": "block",
    "body": {
      "block": {
        "vtx": [],
        "vchBlockSig": "00"
      }
    }
  }
```

**Comment by lateminer** [comment]
Should be solved by this commit: https://github.com/CoinBlack/blackcoin-more/commit/0aff5bfe03d45be365e82bfec6c02abe56776d19
Please confirm.

**Comment by BlackcoinDev** [comment]
I can confirm it is solved
